#!/usr/bin/env bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

echo 'Install powerlevel10k'
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

echo 'Install zsh-autosuggestions'
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

#########################################################
### Setup Symlinks
#########################################################
# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink powerlevel10k prefs
rm $HOME/.p10k.zsh
ln -s $HOME/.dotfiles/shell/.p10k.zsh $HOME/.p10k.zsh

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Symlink yarn prefs
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc

#########################################################
### Setup composer, brew and mas-cli
#########################################################

echo 'Install homebrew...'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install composer'
brew install composer

echo 'Install mas'
brew install mas

#########################################################
### Install common dev/shell tools
#########################################################
echo "Installing ZSH syntax highlighting"
brew install zsh-syntax-hightlighting

echo 'Install Github CLI...'
brew install gh

echo 'Install Git Flow...'
brew install git-flow-avh

echo 'Install z...'
brew install z

echo 'Install pkg-config...'
brew install pkg-config

echo 'Install wget...'
brew install wget

echo 'Install httpie...'
brew install httpie

echo 'Install ncdu...'
brew install ncdu

echo 'Install hub...'
brew install hub

echo 'Install ack...'
brew install ack

echo 'Install doctl...'
brew install doctl

echo 'Install webp...'
brew install webp

echo 'Install docker...'
brew install --cask docker
brew install docker-compose

#########################################################
### Install PHP
#########################################################
echo 'Install PHP 7.4...'
brew install php@7.4
brew link php@7.4 --force

echo 'Install imagemagick...'
brew install imagemagick

echo 'Install imagick...'
pecl install imagick

#########################################################
### Install NodeJS
#########################################################
echo 'Install node...'
brew install node

npm install -g n

n lts

echo 'Install yarn...'
brew install yarn

echo 'Install gulp-cli...'
npm install gulp-cli -g

########################################################
### Install Go
########################################################

echo 'Install Go'
brew install go

echo 'Install Go Doc'
go get golang.org/x/tools/cmd/godoc

echo 'Install Go Lint'
go get golang.org/x/lint/golint

#########################################################
### Install GUI tools and software
#########################################################
echo 'Install Google Chrome...'
brew install --cask google-chrome

echo 'Install Postman...'
brew install --cask postman

echo 'Install iterm2...'
brew install --cask iterm2

echo 'Install Jetbrains Toolbox...'
brew install --cask jetbrains-toolbox

echo 'Install Slack...'
brew install --cask slack

echo 'Install 1Password...'
brew install --cask 1password

echo 'Install Responsively...'
brew install --cask responsively

echo 'Install Spotify...'
brew install --cask spotify

echo 'Install numi...'
brew install --cask numi

echo 'Install Bartender...'
brew install --cask bartender

echo 'Install Toggl Track...'
brew install --cask toggl-track

echo 'Install Sky Fonts...'
brew install --cask skyfonts

echo 'Install Dropbox...'
brew install --cask dropbox

echo 'Install Figma'
brew install --cask figma

echo 'Install TablePlus'
brew install --cask tableplus

echo 'Install Telegram'
brew install --cask telegram

echo 'Install Visual Studio Code'
brew install --cask visual-studio-code

echo 'Install Cleanshot X'
brew install --cask cleanshot

echo 'Install Tripmode'
brew install --cask tripmode

echo 'Install WhatsApp Desktop'
mas install 1147396723

echo 'Install Magnet...'
mas install 441258766

echo 'Install The Unarchiver...'
mas install 425424353

echo 'Install Jira Cloud for Mac...'
mas install 1475897096

echo 'Install Teamviewer...'
brew install --cask teamviewer

echo 'Install Steam...'
brew install --cask steam

echo 'Install HEY...'
brew install --cask hey

echo 'Install Discord...'
brew install --cask discord

echo 'Install AdGuard'
mas install 1440147259

echo "Install Microsoft 365 apps..."
echo "Install Word..."
mas install 462054704
echo "Install Excel..."
mas install 462058435
echo "Install PowerPoint..."
mas install 462062816
echo "Install Outlook..."
mas install 985367838
echo "Install Onedrive..."
mas install 823766827

echo 'Install Xcode...'
mas install 497799835

###################################################################
### Install Jale
###################################################################
echo 'Install Jale...'
npm i -g jale

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the powerlevel10k terminal theme work:'
echo '1. Install fonts included in ~/.dotfiles/misc'
echo '2. Install theme included in ~/.dotfiles/misc'
echo '3. Install Jale with jale install'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo "1. Set some sensible MacOS defaults by running: $HOME/.dotfiles/macos/set-defaults.sh"
echo "2. Make a .dotfiles-custom/shell/.aliases for your personal commands"

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
